### ISSUE TITLE
getPools fails

### ISSUE THREAD

**Issue by LinuxIsCool** [balancer/balpy#39]
```$python samples/theGraph/getPools.py    ```

```
Usage: python samples/theGraph/getPools.py <network>
No network given; defaulting to mainnet Ethereum
Querying number of pools...
Got response from the Subgraph
Querying 953 pools...
Querying pools # 0 through # 5 ...
Got pools.
Querying tokens for pool with ID: 0x0017c363b29d8f86d82e9681552685f68f34b7e4000200000000000000000209
Traceback (most recent call last):
  File "/home/ygg/Workspace/Forks/balpy/samples/theGraph/getPools.py", line 33, in <module>
    main();
  File "/home/ygg/Workspace/Forks/balpy/samples/theGraph/getPools.py", line 29, in main
    pools = bg.getV2Pools(batch_size, verbose=verbose)
  File "/home/ygg/Workspace/Forks/balpy/balpy/graph/graph.py", line 190, in getV2Pools
    curr_pool_token_data = self.getPoolTokens(curr_id, verbose=verbose);
  File "/home/ygg/Workspace/Forks/balpy/balpy/graph/graph.py", line 111, in getPoolTokens
    response = self.client.execute(gql(formatted_query_string))
  File "/home/ygg/.cache/pypoetry/virtualenvs/balpy-yyw1STJO-py3.10/lib/python3.10/site-packages/gql/client.py", line 78, in execute
    raise Exception(str(result.errors[0]))
Exception: {'locations': [{'column': 5, 'line': 12}], 'message': 'Type `PoolToken` has no field `invested`'}
```

**Comment by omidkhs** [comment]
it fails for me too!
